# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('giftee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Participant')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.List')),
            ],
        ),
    ]
