# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20170410_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='giftee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Participant'),
        ),
    ]
